# This file is used by Acquia Pipelines continuous integration. It builds MCS
# Profile and runs its tests. Upon success, an artifact is deployed to the
# mcsprofilenightly (43e3a91e-5cb3-4f3d-8ecb-4b6653422e0e) sub on Acquia cloud.
version: 1.1.0
services:
  - mysql
  - php:
      version: 7.1

events:
  build:
    steps:
      - setup:
          type: script
          script:
            # Add Composer's local bin directory to the PATH so that we will be
            # running our installed versions of Drush, PHPCS, Behat, etc.
            - export PATH="$HOME/.composer/vendor/bin:$SOURCE_DIR/bin:$PATH"
            - composer validate --no-check-all --ansi
            - composer install
      - install:
          type: script
          script:
            - cd $SOURCE_DIR
            - mysql -u root -proot -e 'CREATE DATABASE drupal;'
            - phing install -Ddb.password=root -Ddb.database=drupal -Durl=http://127.0.0.1:8080
      - test:
          type: script
          script:
            - cd $SOURCE_DIR/docroot
            - drush runserver --default-server=builtin 8080 &>/dev/null &
            - phantomjs --webdriver=4444 > /dev/null &
            - sleep 10
            - phpunit --configuration ./core --group mcs
            - behat --stop-on-failure --config ./sites/default/files/behat.yml --tags=mcs --tags=~javascript
      - cleanup:
          type: script
          script:
            - cd $SOURCE_DIR
            # Remove drush so our version doesn't interfere with cloud commands.
            - composer remove drush/drush --dev
            # Setup settings file and codebase with minimum required for cloud.
            - phing cloud-settings
