<?php

/**
 * @file
 * Install, update and uninstall hooks for the MCS sub-profile.
 */

use Drupal\user\RoleInterface;

/**
 * Implements hook_install().
 */
function mcs_profile_install() {
  user_role_grant_permissions(RoleInterface::AUTHENTICATED_ID, ['access toolbar']);

  \Drupal::configFactory()
    ->getEditable('system.theme')
    ->set('default', 'material_admin')
    ->set('admin', 'material_admin')
    ->save();

}
